# Generated by Django 4.2.13 on 2024-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('short_text', models.TextField()),
            ],
        ),
    ]
